import { parseClassWorkspace } from "./class-workspace";

export const demoClass = parseClassWorkspace({
  id: "klasse-7b",
  name: "Klasse 7b",
  teacherName: "Frau Sommer",
  schoolYear: "2026/27",
  enabledModules: ["vocabulary", "german", "mathematics", "typing"],
  todayPractice: [
    {
      id: "vocabulary-due",
      title: "Fällige Vokabeln",
      module: "vocabulary",
      reason: "due",
      amount: 8,
      route: "/klasse/7b/aufgaben/vokabeln",
      rankingEligible: true,
    },
    {
      id: "math-errors",
      title: "Brüche wiederholen",
      module: "mathematics",
      reason: "error",
      amount: 5,
      route: "/klasse/7b/aufgaben/mathematik",
      rankingEligible: true,
    },
    {
      id: "german-due",
      title: "Dehnungs-h üben",
      module: "german",
      reason: "teacher",
      amount: 6,
      route: "/klasse/7b/aufgaben/deutsch",
      rankingEligible: true,
    },
  ],
  assignments: [
    {
      id: "english-school-words",
      title: "School words · Teil 1",
      module: "vocabulary",
      description: "Übe die neuen Vokabeln in beide Richtungen.",
      route: "/klasse/7b/aufgaben/vokabeln",
      status: "in-progress",
      rankingEligible: true,
      dueLabel: "bis Freitag",
    },
    {
      id: "typing-home-row",
      title: "Tipptraining · Grundreihe",
      module: "typing",
      description: "Trainiere die Grundstellung mit ruhigem Rhythmus.",
      route: "/klasse/7b/aufgaben/tippen",
      status: "new",
      rankingEligible: true,
      dueLabel: "bis Montag",
    },
    {
      id: "german-memory-words",
      title: "Merkwörter mit Dehnungs-h",
      module: "german",
      description: "Bearbeite die freigeschalteten Merkstufen.",
      route: "/klasse/7b/aufgaben/deutsch",
      status: "completed",
      rankingEligible: true,
    },
  ],
});
