import { textboxTextSchema, type TextboxText } from "./textbox-text";

/**
 * Welle 1: 15 Texte (je 5 pro Schwierigkeit). Die Texte sind ein Entwurf und
 * werden von der Lehrkraft fachlich geprüft (siehe docs/inhalte/textbox.md).
 */
const DRAFT_TEXTS: readonly TextboxText[] = [
  // ── Leicht ────────────────────────────────────────────────────────────
  {
    id: "TXT-001",
    title: "Der kleine Hund",
    difficulty: "leicht",
    phenomena: ["doppelkonsonanten"],
    genre: "geschichte",
    text: "Im Garten wohnt ein kleiner Hund. Er heißt Bello und liebt seinen Ball. Jeden Morgen rennt er über die Wiese. Dann kommt die Katze und will mitspielen. Bello bellt laut vor Freude. Am Abend schläft er müde in seinem Körbchen.",
    targetWords: ["Bello", "Ball", "rennt", "Dann", "kommt", "will", "bellt"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-002",
    title: "Mein Schulweg",
    difficulty: "leicht",
    phenomena: ["dehnungs-h"],
    genre: "schule",
    text: "Ich wohne nah bei der Schule. Jeden Morgen fahre ich mit dem Fahrrad dorthin. Dort wartet schon mein Freund Jan. Um acht Uhr kommt unsere Lehrerin. Sie zählt alle Kinder und lächelt. Dann beginnt der Unterricht.",
    targetWords: [
      "wohne",
      "nah",
      "fahre",
      "Fahrrad",
      "Uhr",
      "Lehrerin",
      "zählt",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-003",
    title: "Am Bach",
    difficulty: "leicht",
    phenomena: ["ie"],
    genre: "erlebnis",
    text: "Wir spielen am Bach. Das Wasser ist kalt und klar. Mein Bruder fliegt mit dem Drachen über die Wiese. Ich sehe eine Biene und ein kleines Tier im Gras. Es ist ein schöner Tag und wir haben viel Spaß.",
    targetWords: ["spielen", "fliegt", "Wiese", "Biene", "Tier", "viel"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-004",
    title: "Beim Bäcker",
    difficulty: "leicht",
    phenomena: ["s-ss-sz"],
    genre: "alltag",
    text: "Heute gehe ich zum Bäcker. Ich muss Brot und süße Brötchen kaufen. Die Straße ist heiß und der Laden ist voll. Die Bäckerin lässt mich ein Stück probieren. Es schmeckt sehr gut. Ich esse es auf und trage die Tüte nach Hause. Dort essen wir alle zusammen.",
    targetWords: ["muss", "süße", "Straße", "heiß", "lässt", "esse", "essen"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-005",
    title: "Der Hase im Wald",
    difficulty: "leicht",
    phenomena: ["auslautverhaertung"],
    genre: "sachtext",
    text: "Im Wald lebt ein Hase. Er hat ein weiches Fell und lange Ohren. Am Tag versteckt er sich im Gras. Abends geht er auf Futtersuche. Er läuft über den Weg bis zum Feld am Berg. Ein Hund kann ihn nur schwer finden. Das Kind sieht ihn manchmal von weitem.",
    targetWords: ["Wald", "Tag", "Weg", "Feld", "Berg", "Hund", "Kind"],
    usage: ["frei", "wortspeicher"],
  },
  // ── Mittel ────────────────────────────────────────────────────────────
  {
    id: "TXT-006",
    title: "Das Fußballspiel",
    difficulty: "mittel",
    phenomena: ["doppelkonsonanten"],
    genre: "erlebnis",
    text: "Am Samstag haben wir ein wichtiges Fußballspiel. Schon früh am Morgen packe ich meine Tasche. Ich vergesse nicht die Schuhe und die Trinkflasche. Auf dem Sportplatz warten alle Mitspieler. Der Trainer erklärt uns die Aufstellung. Dann pfeift der Schiedsrichter an. Wir rennen über den nassen Rasen und kämpfen um jeden Ball. Kurz vor Schluss schieße ich ein Tor. Alle jubeln und wir fallen uns in die Arme. Am Ende gewinnen wir mit zwei zu eins.",
    targetWords: [
      "Fußballspiel",
      "vergesse",
      "alle",
      "Aufstellung",
      "Dann",
      "rennen",
      "nassen",
      "Ball",
      "Schluss",
      "Alle",
      "fallen",
      "gewinnen",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-007",
    title: "Ein Ausflug zum Zoo",
    difficulty: "mittel",
    phenomena: ["ie"],
    genre: "erlebnis",
    text: "Gestern waren wir mit der ganzen Klasse im Zoo. Zuerst sahen wir die Affen, die auf den Bäumen spielten. Danach fütterten wir die Ziegen. Im Reptilienhaus lag eine riesige Schlange. Mein Freund Tim hatte noch nie ein Nashorn gesehen. Er blieb lange vor dem Gehege stehen und bestaunte die Tiere. Auch die Wiese mit den Zebras gefiel uns sehr. Wir wollten gar nicht wieder gehen. Zum Abschied kauften wir noch ein Eis.",
    targetWords: [
      "spielten",
      "Ziegen",
      "riesige",
      "nie",
      "Tiere",
      "Wiese",
      "gefiel",
      "wieder",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-008",
    title: "Unser Klassenzimmer",
    difficulty: "mittel",
    phenomena: ["gross-klein"],
    genre: "schule",
    text: "In unserem Klassenzimmer gibt es viele Dinge. An der Wand hängt eine große Landkarte. Die Tafel steht neben dem Fenster. Auf dem Regal liegen Bücher, Hefte und Stifte. Jedes Kind hat einen Tisch und einen Stuhl. In der Pause essen wir ein Brot und trinken Wasser. Unsere Lehrerin schreibt den Plan für den Tag an die Tafel. Wir lesen, rechnen und malen gern. Am Freitag räumen wir gemeinsam auf.",
    targetWords: [
      "Klassenzimmer",
      "Wand",
      "Landkarte",
      "Tafel",
      "Fenster",
      "Regal",
      "Bücher",
      "Tisch",
      "Stuhl",
      "Pause",
      "Lehrerin",
      "Plan",
      "Freitag",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-009",
    title: "Wie Bienen leben",
    difficulty: "mittel",
    phenomena: ["auslautverhaertung"],
    genre: "sachtext",
    text: "Bienen leben in einem Volk. In einem Stock wohnen viele tausend Tiere. Im Sommer fliegen sie weit über das Land und sammeln Nektar. Auf jedem Flug besuchen sie viele Blumen und tragen Staub von Blüte zu Blüte. Manche Völker leben in einem hohlen Baum im Wald. Ein Imker stellt die Stöcke an einen Weg am Feld unter dem Berg. Im Stock machen die Bienen aus dem Nektar süßen Honig. Der Honig wird in Waben gelagert, die an der Wand hängen. Im Winter bleibt das Volk im warmen Stock. Jedes Kind kennt das Summen der Bienen am Tag.",
    targetWords: [
      "tausend",
      "Land",
      "Flug",
      "Staub",
      "Wald",
      "Weg",
      "Feld",
      "Berg",
      "Wand",
      "Kind",
      "Tag",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-010",
    title: "Der Regentag",
    difficulty: "mittel",
    phenomena: ["dehnungs-h", "vokallaenge"],
    genre: "alltag",
    text: "Heute regnet es den ganzen Tag. Ich sehe aus dem Fenster und zähle die Tropfen. Meine Mutter nimmt den Schirm und geht zur Arbeit. Mein Bruder fehlt in der Schule, weil er krank ist. Er bleibt im Bett und wärmt sich mit einer Decke. Ich bringe ihm einen Tee. Danach lesen wir zusammen ein Buch über Piraten. Am Nachmittag hört der Regen auf und ein Vogel singt im Baum.",
    targetWords: [
      "zähle",
      "Mutter",
      "nimmt",
      "fehlt",
      "Bett",
      "ihm",
      "Tee",
      "zusammen",
      "Nachmittag",
    ],
    usage: ["frei", "wortspeicher"],
  },
  // ── Schwer ────────────────────────────────────────────────────────────
  {
    id: "TXT-011",
    title: "Die Reise nach Hamburg",
    difficulty: "schwer",
    phenomena: ["gemischt", "doppelkonsonanten", "dehnungs-h", "s-ss-sz"],
    genre: "erlebnis",
    text: "In den Ferien fuhren wir mit dem Zug nach Hamburg. Die Fahrt dauerte mehrere Stunden, aber mir wurde nie langweilig. Ich schaute aus dem Fenster und sah Felder, Wälder und viele kleine Dörfer. In Hamburg wartete schon meine Tante am Bahnhof. Sie nahm uns herzlich in den Arm und brachte uns zu ihrer Wohnung. Am nächsten Morgen besichtigten wir den großen Hafen. Dort lagen riesige Schiffe, die Container aus der ganzen Welt transportieren. Ein Kapitän erklärte uns, wie lange so eine Reise über das Meer dauert. Am Nachmittag aßen wir ein Eis an der Elbe und beobachteten die Möwen. Abends fielen wir müde ins Bett. Diese Tage werde ich nie vergessen.",
    targetWords: [
      "Fahrt",
      "mehrere",
      "fuhren",
      "sah",
      "Bahnhof",
      "nahm",
      "Wohnung",
      "großen",
      "Schiffe",
      "aßen",
      "vergessen",
      "Nachmittag",
      "Bett",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-012",
    title: "Das Geheimnis der alten Mühle",
    difficulty: "schwer",
    phenomena: ["doppelkonsonanten", "dehnungs-h"],
    genre: "geschichte",
    text: "Am Rand des Dorfes steht eine alte Mühle. Niemand wohnt mehr dort, doch die Kinder erzählen sich geheimnisvolle Geschichten. Eines Nachmittags nahmen Lena und Tom ihren ganzen Mut zusammen. Sie schlichen leise zum Eingang und öffneten die knarrende Tür. Im Inneren roch es nach Staub und altem Holz. Plötzlich hörten sie ein Rascheln. Lena hielt die Luft an, während Tom die Taschenlampe hochhob. In der Ecke saß eine kleine Eule. Sie blinzelte die beiden verwundert an. Die Kinder lachten erleichtert. Am Abend erzählten sie ihrem Großvater alles. Er lächelte und sagte, dass jede alte Mühle ihre Geheimnisse hütet. Von nun an besuchten sie die Mühle jede Woche und brachten der Eule Futter mit. Das war ihr schönstes Geheimnis.",
    targetWords: [
      "Mühle",
      "wohnt",
      "mehr",
      "erzählen",
      "Nachmittags",
      "nahmen",
      "öffneten",
      "während",
      "erzählten",
      "alles",
      "Futter",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-013",
    title: "Wasser auf der Erde",
    difficulty: "schwer",
    phenomena: ["zusammensetzungen"],
    genre: "sachtext",
    text: "Wasser ist die Grundlage allen Lebens. Es bedeckt mehr als zwei Drittel unserer Erde. Den größten Teil davon bilden die Meere. Ihr Meerwasser ist sehr salzig. Trinkwasser findet man dagegen in Flüssen, Seen und im Grundwasser. Die Sonne lässt Wasser verdunsten und es steigt als Wasserdampf nach oben. In der Höhe bilden sich Regenwolken. Wenn die Tropfen zu schwer werden, fällt Regen oder Schnee zurück zur Erde. Mit Schneeflocken und Regentropfen schließt sich der Wasserkreislauf. An manchen Orten stürzt das Wasser als Wasserfall in die Tiefe. Auch Pflanzen und Tiere sind auf Wasser angewiesen. Ohne Regen würden die Felder vertrocknen. Nach starkem Regen kann dagegen Hochwasser entstehen. Viele Familien sammeln Regenwasser in einer Regentonne und gießen damit ihren Gemüsegarten. Deshalb sollten wir sparsam damit umgehen und die Gewässer sauber halten.",
    targetWords: [
      "Grundlage",
      "Meerwasser",
      "Trinkwasser",
      "Grundwasser",
      "Wasserdampf",
      "Regenwolken",
      "Schneeflocken",
      "Regentropfen",
      "Wasserkreislauf",
      "Wasserfall",
      "Hochwasser",
      "Regenwasser",
      "Regentonne",
      "Gemüsegarten",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-014",
    title: "Die Klassenfahrt",
    difficulty: "schwer",
    phenomena: ["wortbausteine"],
    genre: "schule",
    text: "Im Frühling fuhr unsere Klasse für drei Tage ins Schullandheim. Die Vorbereitung hatte schon Wochen vorher begonnen. Wir packten Schlafsäcke, Taschenlampen und warme Kleidung ein. Am Abfahrtstag verabschiedeten wir uns von unseren Eltern. Im Bus sangen wir fröhliche Lieder. Im Schullandheim bezogen wir unsere Zimmer und erkundeten das Gelände. Am zweiten Tag unternahmen wir eine Wanderung durch den Wald. Unterwegs entdeckten wir Spuren von Rehen und Wildschweinen. Abends versammelten wir uns am Lagerfeuer. Unsere Lehrerin erzählte eine spannende Geschichte. Am letzten Abend veranstalteten wir eine Abschlussfeier mit Spielen und Musik. Danach verpackten wir unsere Koffer und erholten uns bei einem Becher Kakao. Die Erinnerung an diese Fahrt wird uns lange begleiten.",
    targetWords: [
      "Vorbereitung",
      "begonnen",
      "verabschiedeten",
      "Abfahrtstag",
      "erkundeten",
      "unternahmen",
      "Wanderung",
      "entdeckten",
      "versammelten",
      "veranstalteten",
      "Abschlussfeier",
      "verpackten",
      "erholten",
      "Erinnerung",
      "begleiten",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-015",
    title: "Der Wochenmarkt",
    difficulty: "schwer",
    phenomena: ["gross-klein"],
    genre: "alltag",
    text: "Jeden Samstag findet auf dem Marktplatz unserer Stadt der Wochenmarkt statt. Schon früh am Morgen bauen die Händler ihre Stände auf. Es duftet nach frischem Brot, reifem Obst und gebratenen Würstchen. Meine Oma kauft dort immer Gemüse, Eier und Käse. Der Bauer erklärt ihr, dass die Äpfel aus seinem eigenen Garten stammen. Ich darf eine Tüte Kirschen tragen und probiere heimlich eine. Am Fischstand kostet das Pfund Lachs heute nur wenig. Der Verkäufer lacht freundlich und packt den Fisch ein. Neben dem Blumenstand spielt ein Musiker auf seiner Gitarre. Viele Menschen bleiben stehen und hören zu. Zum Schluss kaufen wir noch einen Strauß Tulpen für das Wohnzimmer. Mit vollen Taschen gehen wir zufrieden nach Hause.",
    targetWords: [
      "Samstag",
      "Marktplatz",
      "Wochenmarkt",
      "Händler",
      "Stände",
      "Obst",
      "Gemüse",
      "Käse",
      "Bauer",
      "Äpfel",
      "Garten",
      "Kirschen",
      "Blumenstand",
      "Musiker",
      "Gitarre",
      "Strauß",
      "Tulpen",
      "Wohnzimmer",
      "Fischstand",
      "Lachs",
      "Verkäufer",
    ],
    usage: ["frei", "wortspeicher"],
  },
];

export const TEXTBOX_TEXTS: readonly TextboxText[] = DRAFT_TEXTS.map((text) =>
  textboxTextSchema.parse(text),
);

export function getTextboxText(id: string): TextboxText | undefined {
  return TEXTBOX_TEXTS.find((text) => text.id === id);
}
