import { textboxTextSchema, type TextboxText } from "./textbox-text";

/**
 * Welle 1 (TXT-001 bis TXT-015) und Welle 2 (TXT-016 bis TXT-050). Die Texte sind ein Entwurf und
 * werden von der Lehrkraft fachlich geprüft (siehe docs/inhalte/textbox.md).
 */
const DRAFT_TEXTS: readonly TextboxText[] = [
  // ── Leicht ────────────────────────────────────────────────────────────
  {
    id: "TXT-001",
    title: "Der kleine Hund",
    difficulty: "leicht",
    phenomena: ["doppelkonsonanten"],
    genre: "geschichte",
    text: "Im Garten wohnt ein kleiner Hund. Er heißt Bello und liebt seinen Ball. Jeden Morgen rennt er über die Wiese. Dann kommt die Katze und will mitspielen. Bello bellt laut vor Freude. Am Abend schläft er müde in seinem Körbchen.",
    targetWords: ["Bello", "Ball", "rennt", "Dann", "kommt", "will", "bellt"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-002",
    title: "Mein Schulweg",
    difficulty: "leicht",
    phenomena: ["dehnungs-h"],
    genre: "schule",
    text: "Ich wohne nah bei der Schule. Jeden Morgen fahre ich mit dem Fahrrad dorthin. Dort wartet schon mein Freund Jan. Um acht Uhr kommt unsere Lehrerin. Sie zählt alle Kinder und lächelt. Dann beginnt der Unterricht.",
    targetWords: [
      "wohne",
      "nah",
      "fahre",
      "Fahrrad",
      "Uhr",
      "Lehrerin",
      "zählt",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-003",
    title: "Am Bach",
    difficulty: "leicht",
    phenomena: ["ie"],
    genre: "erlebnis",
    text: "Wir spielen am Bach. Das Wasser ist kalt und klar. Mein Bruder fliegt mit dem Drachen über die Wiese. Ich sehe eine Biene und ein kleines Tier im Gras. Es ist ein schöner Tag und wir haben viel Spaß.",
    targetWords: ["spielen", "fliegt", "Wiese", "Biene", "Tier", "viel"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-004",
    title: "Beim Bäcker",
    difficulty: "leicht",
    phenomena: ["s-ss-sz"],
    genre: "alltag",
    text: "Heute gehe ich zum Bäcker. Ich muss Brot und süße Brötchen kaufen. Die Straße ist heiß und der Laden ist voll. Die Bäckerin lässt mich ein Stück probieren. Es schmeckt sehr gut. Ich esse es auf und trage die Tüte nach Hause. Dort essen wir alle zusammen.",
    targetWords: ["muss", "süße", "Straße", "heiß", "lässt", "esse", "essen"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-005",
    title: "Der Hase im Wald",
    difficulty: "leicht",
    phenomena: ["auslautverhaertung"],
    genre: "sachtext",
    text: "Im Wald lebt ein Hase. Er hat ein weiches Fell und lange Ohren. Am Tag versteckt er sich im Gras. Abends geht er auf Futtersuche. Er läuft über den Weg bis zum Feld am Berg. Ein Hund kann ihn nur schwer finden. Das Kind sieht ihn manchmal von weitem.",
    targetWords: ["Wald", "Tag", "Weg", "Feld", "Berg", "Hund", "Kind"],
    usage: ["frei", "wortspeicher"],
  },
  // ── Mittel ────────────────────────────────────────────────────────────
  {
    id: "TXT-006",
    title: "Das Fußballspiel",
    difficulty: "mittel",
    phenomena: ["doppelkonsonanten"],
    genre: "erlebnis",
    text: "Am Samstag haben wir ein wichtiges Fußballspiel. Schon früh am Morgen packe ich meine Tasche. Ich vergesse nicht die Schuhe und die Trinkflasche. Auf dem Sportplatz warten alle Mitspieler. Der Trainer erklärt uns die Aufstellung. Dann pfeift der Schiedsrichter an. Wir rennen über den nassen Rasen und kämpfen um jeden Ball. Kurz vor Schluss schieße ich ein Tor. Alle jubeln und wir fallen uns in die Arme. Am Ende gewinnen wir mit zwei zu eins.",
    targetWords: [
      "Fußballspiel",
      "vergesse",
      "alle",
      "Aufstellung",
      "Dann",
      "rennen",
      "nassen",
      "Ball",
      "Schluss",
      "Alle",
      "fallen",
      "gewinnen",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-007",
    title: "Ein Ausflug zum Zoo",
    difficulty: "mittel",
    phenomena: ["ie"],
    genre: "erlebnis",
    text: "Gestern waren wir mit der ganzen Klasse im Zoo. Zuerst sahen wir die Affen, die auf den Bäumen spielten. Danach fütterten wir die Ziegen. Im Reptilienhaus lag eine riesige Schlange. Mein Freund Tim hatte noch nie ein Nashorn gesehen. Er blieb lange vor dem Gehege stehen und bestaunte die Tiere. Auch die Wiese mit den Zebras gefiel uns sehr. Wir wollten gar nicht wieder gehen. Zum Abschied kauften wir noch ein Eis.",
    targetWords: [
      "spielten",
      "Ziegen",
      "riesige",
      "nie",
      "Tiere",
      "Wiese",
      "gefiel",
      "wieder",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-008",
    title: "Unser Klassenzimmer",
    difficulty: "mittel",
    phenomena: ["gross-klein"],
    genre: "schule",
    text: "In unserem Klassenzimmer gibt es viele Dinge. An der Wand hängt eine große Landkarte. Die Tafel steht neben dem Fenster. Auf dem Regal liegen Bücher, Hefte und Stifte. Jedes Kind hat einen Tisch und einen Stuhl. In der Pause essen wir ein Brot und trinken Wasser. Unsere Lehrerin schreibt den Plan für den Tag an die Tafel. Wir lesen, rechnen und malen gern. Am Freitag räumen wir gemeinsam auf.",
    targetWords: [
      "Klassenzimmer",
      "Wand",
      "Landkarte",
      "Tafel",
      "Fenster",
      "Regal",
      "Bücher",
      "Tisch",
      "Stuhl",
      "Pause",
      "Lehrerin",
      "Plan",
      "Freitag",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-009",
    title: "Wie Bienen leben",
    difficulty: "mittel",
    phenomena: ["auslautverhaertung"],
    genre: "sachtext",
    text: "Bienen leben in einem Volk. In einem Stock wohnen viele tausend Tiere. Am Tag fliegen sie weit über das Land und sammeln Nektar. Auf jedem Flug besuchen sie Blumen auf dem Feld, im Wald und im Garten. Dabei bleibt Blütenstaub an ihrem Körper haften. Sie finden den Weg zurück, auch wenn der Wind weht. Im Stock machen die Bienen aus dem Nektar süßen Honig. Im Winter bleibt das Volk im warmen Stock und lebt von seinem Vorrat.",
    targetWords: [
      "tausend",
      "Tag",
      "Land",
      "Flug",
      "Feld",
      "Wald",
      "Weg",
      "Wind",
      "Blütenstaub",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-010",
    title: "Der Regentag",
    difficulty: "mittel",
    phenomena: ["dehnungs-h", "vokallaenge"],
    genre: "alltag",
    text: "Heute regnet es den ganzen Tag. Ich sehe aus dem Fenster und zähle die Tropfen. Meine Mutter nimmt den Schirm und geht zur Arbeit. Mein Bruder fehlt in der Schule, weil er krank ist. Er bleibt im Bett und wärmt sich mit einer Decke. Ich bringe ihm einen Tee. Danach lesen wir zusammen ein Buch über Piraten. Am Nachmittag hört der Regen auf und ein Vogel singt im Baum.",
    targetWords: [
      "zähle",
      "Mutter",
      "nimmt",
      "fehlt",
      "Bett",
      "ihm",
      "Tee",
      "zusammen",
      "Nachmittag",
    ],
    usage: ["frei", "wortspeicher"],
  },
  // ── Schwer ────────────────────────────────────────────────────────────
  {
    id: "TXT-011",
    title: "Die Reise nach Hamburg",
    difficulty: "schwer",
    phenomena: ["gemischt", "doppelkonsonanten", "dehnungs-h", "s-ss-sz"],
    genre: "erlebnis",
    text: "In den Ferien fuhren wir mit dem Zug nach Hamburg. Die Fahrt dauerte mehrere Stunden, aber mir wurde nie langweilig. Ich schaute aus dem Fenster und sah Felder, Wälder und viele kleine Dörfer. In Hamburg wartete schon meine Tante am Bahnhof. Sie nahm uns herzlich in den Arm und brachte uns zu ihrer Wohnung. Am nächsten Morgen besichtigten wir den großen Hafen. Dort lagen riesige Schiffe, die Container aus der ganzen Welt transportieren. Ein Kapitän erklärte uns, wie lange so eine Reise über das Meer dauert. Am Nachmittag aßen wir ein Eis an der Elbe und beobachteten die Möwen. Abends fielen wir müde ins Bett. Diese Tage werde ich nie vergessen.",
    targetWords: [
      "Fahrt",
      "mehrere",
      "fuhren",
      "sah",
      "Bahnhof",
      "nahm",
      "Wohnung",
      "großen",
      "Schiffe",
      "aßen",
      "vergessen",
      "Nachmittag",
      "Bett",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-012",
    title: "Das Geheimnis der alten Mühle",
    difficulty: "schwer",
    phenomena: ["doppelkonsonanten", "dehnungs-h"],
    genre: "geschichte",
    text: "Am Rand des Dorfes steht eine alte Mühle. Niemand wohnt mehr dort, doch die Kinder erzählen sich geheimnisvolle Geschichten. Eines Nachmittags nahmen Lena und Tom ihren ganzen Mut zusammen. Sie schlichen leise zum Eingang und öffneten die knarrende Tür. Im Inneren roch es nach Staub und altem Holz. Plötzlich hörten sie ein Rascheln. Lena hielt die Luft an, während Tom die Taschenlampe hochhob. In der Ecke saß eine kleine Eule. Sie blinzelte die beiden verwundert an. Die Kinder lachten erleichtert. Am Abend erzählten sie ihrem Großvater alles. Er lächelte und sagte, dass jede alte Mühle ihre Geheimnisse hütet. Von nun an besuchten sie die Mühle jede Woche und brachten der Eule Futter mit. Das war ihr schönstes Geheimnis.",
    targetWords: [
      "Mühle",
      "wohnt",
      "mehr",
      "erzählen",
      "Nachmittags",
      "nahmen",
      "öffneten",
      "während",
      "erzählten",
      "alles",
      "Futter",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-013",
    title: "Wasser auf der Erde",
    difficulty: "schwer",
    phenomena: ["zusammensetzungen"],
    genre: "sachtext",
    text: "Wasser ist die Grundlage allen Lebens. Es bedeckt mehr als zwei Drittel unserer Erde. Den größten Teil davon bilden die Meere. Ihr Meerwasser ist sehr salzig. Trinkwasser findet man dagegen in Flüssen, Seen und im Grundwasser. Die Sonne lässt Wasser verdunsten und es steigt als Wasserdampf nach oben. In der Höhe bilden sich Regenwolken. Wenn die Tropfen zu schwer werden, fällt Regen oder Schnee zurück zur Erde. Mit Schneeflocken und Regentropfen schließt sich der Wasserkreislauf. An manchen Orten stürzt das Wasser als Wasserfall in die Tiefe. Auch Pflanzen und Tiere sind auf Wasser angewiesen. Ohne Regen würden die Felder vertrocknen. Nach starkem Regen kann dagegen Hochwasser entstehen. Viele Familien sammeln Regenwasser in einer Regentonne und gießen damit ihren Gemüsegarten. Deshalb sollten wir sparsam damit umgehen und die Gewässer sauber halten.",
    targetWords: [
      "Grundlage",
      "Meerwasser",
      "Trinkwasser",
      "Grundwasser",
      "Wasserdampf",
      "Regenwolken",
      "Schneeflocken",
      "Regentropfen",
      "Wasserkreislauf",
      "Wasserfall",
      "Hochwasser",
      "Regenwasser",
      "Regentonne",
      "Gemüsegarten",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-014",
    title: "Die Klassenfahrt",
    difficulty: "schwer",
    phenomena: ["wortbausteine"],
    genre: "schule",
    text: "Im Frühling fuhr unsere Klasse für drei Tage ins Schullandheim. Die Vorbereitung hatte schon Wochen vorher begonnen. Wir packten Schlafsäcke, Taschenlampen und warme Kleidung ein. Am Abfahrtstag verabschiedeten wir uns von unseren Eltern. Im Bus sangen wir fröhliche Lieder. Im Schullandheim bezogen wir unsere Zimmer und erkundeten das Gelände. Am zweiten Tag unternahmen wir eine Wanderung durch den Wald. Unterwegs entdeckten wir Spuren von Rehen und Wildschweinen. Abends versammelten wir uns am Lagerfeuer. Unsere Lehrerin erzählte eine spannende Geschichte. Am letzten Abend veranstalteten wir eine Abschlussfeier mit Spielen und Musik. Danach verpackten wir unsere Koffer und erholten uns bei einem Becher Kakao. Die Erinnerung an diese Fahrt wird uns lange begleiten.",
    targetWords: [
      "Vorbereitung",
      "begonnen",
      "verabschiedeten",
      "Abfahrtstag",
      "erkundeten",
      "unternahmen",
      "Wanderung",
      "entdeckten",
      "versammelten",
      "veranstalteten",
      "Abschlussfeier",
      "verpackten",
      "erholten",
      "Erinnerung",
      "begleiten",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-015",
    title: "Der Wochenmarkt",
    difficulty: "schwer",
    phenomena: ["gross-klein"],
    genre: "alltag",
    text: "Jeden Samstag findet auf dem Marktplatz unserer Stadt der Wochenmarkt statt. Schon früh am Morgen bauen die Händler ihre Stände auf. Es duftet nach frischem Brot, reifem Obst und gebratenen Würstchen. Meine Oma kauft dort immer Gemüse, Eier und Käse. Der Bauer erklärt ihr, dass die Äpfel aus seinem eigenen Garten stammen. Ich darf eine Tüte Kirschen tragen und probiere heimlich eine. Am Fischstand kostet das Pfund Lachs heute nur wenig. Der Verkäufer lacht freundlich und packt den Fisch ein. Neben dem Blumenstand spielt ein Musiker auf seiner Gitarre. Viele Menschen bleiben stehen und hören zu. Zum Schluss kaufen wir noch einen Strauß Tulpen für das Wohnzimmer. Mit vollen Taschen gehen wir zufrieden nach Hause.",
    targetWords: [
      "Samstag",
      "Marktplatz",
      "Wochenmarkt",
      "Händler",
      "Stände",
      "Obst",
      "Gemüse",
      "Käse",
      "Bauer",
      "Äpfel",
      "Garten",
      "Kirschen",
      "Blumenstand",
      "Musiker",
      "Gitarre",
      "Strauß",
      "Tulpen",
      "Wohnzimmer",
      "Fischstand",
      "Lachs",
      "Verkäufer",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-016",
    title: "Am Morgen",
    difficulty: "leicht",
    phenomena: ["vokallaenge"],
    genre: "alltag",
    text: "Am Morgen steht Mama früh auf. Sie kocht Tee und schneidet das Brot. Ich lese noch ein Buch im Bett. Dann zieht mich der Duft in die Küche. Wir essen zusammen und reden über den Tag. Danach packe ich meine Tasche und gehe zur Schule.",
    targetWords: [
      "steht",
      "früh",
      "Tee",
      "Bett",
      "zieht",
      "essen",
      "zusammen",
      "gehe",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-017",
    title: "Die Maus und der Mond",
    difficulty: "leicht",
    phenomena: ["vokallaenge"],
    genre: "geschichte",
    text: "Eine kleine Maus sitzt am See. Der Mond scheint hell auf das Wasser. Die Maus sieht ein Boot und fährt mit. Ein Frosch quakt leise im Moos. Dann kommt ein Wind und weht das Boot ans Ufer. Die Maus lacht und rennt nach Hause.",
    targetWords: [
      "See",
      "hell",
      "Wasser",
      "sieht",
      "Boot",
      "fährt",
      "Moos",
      "weht",
      "rennt",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-018",
    title: "Im Schwimmbad",
    difficulty: "leicht",
    phenomena: ["s-ss-sz"],
    genre: "erlebnis",
    text: "Im Sommer ist es heiß. Wir gehen ins Schwimmbad und springen ins Wasser. Das Wasser ist nass und kalt. Auf der Wiese essen wir ein großes Eis. Papa isst eine Brezel. Ich muss mein Handtuch auswringen, weil es ganz nass ist. Am Abend gehen wir müde nach Hause.",
    targetWords: ["heiß", "Wasser", "nass", "essen", "großes", "isst", "muss"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-019",
    title: "Vorlesetag",
    difficulty: "leicht",
    phenomena: ["wortbausteine"],
    genre: "schule",
    text: "In der Schule ist heute Vorlesetag. Unsere Lehrerin erzählt eine spannende Geschichte. Wir verstehen jedes Wort und beginnen zu lachen. Danach dürfen wir ein Bild malen. Ich verrate meinem Freund meine Idee. Zum Schluss zeigen wir alle Bilder.",
    targetWords: [
      "Vorlesetag",
      "erzählt",
      "Geschichte",
      "verstehen",
      "beginnen",
      "verrate",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-020",
    title: "Die Biene",
    difficulty: "leicht",
    phenomena: ["ie"],
    genre: "sachtext",
    text: "Die Biene ist ein kleines Tier. Sie fliegt von Blume zu Blume und sammelt süßen Nektar. Viele Bienen leben in einem Stock. Im Frühling und im Sommer sind sie sehr fleißig. Ohne die Bienen gäbe es nicht so viel Obst.",
    targetWords: ["Biene", "Tier", "fliegt", "Viele", "Bienen", "viel"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-021",
    title: "Einkaufen mit Oma",
    difficulty: "leicht",
    phenomena: ["doppelkonsonanten"],
    genre: "alltag",
    text: "Heute gehe ich mit Oma zum Supermarkt. Wir kaufen Kartoffeln, Butter und Kaffee. Oma will auch Kuchen backen. Im Wagen liegt schon Mehl. Ich fasse die Dose mit beiden Händen und stelle sie vorsichtig in den Wagen. Dann kommen wir an die Kasse und bezahlen.",
    targetWords: [
      "Kartoffeln",
      "Butter",
      "Kaffee",
      "will",
      "fasse",
      "kommen",
      "Kasse",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-022",
    title: "Ein Tag mit Nele",
    difficulty: "leicht",
    phenomena: ["gross-klein"],
    genre: "geschichte",
    text: "Nele hat einen Hund und eine Katze. Am Morgen füttert sie den Hund. Die Katze bekommt Milch. Dann nimmt Nele ihre Tasche und geht zur Schule. Im Garten blühen die Blumen. Ein Vogel singt auf dem Baum.",
    targetWords: [
      "Hund",
      "Katze",
      "Milch",
      "Tasche",
      "Schule",
      "Garten",
      "Blumen",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-023",
    title: "Der Weg zur Schule",
    difficulty: "leicht",
    phenomena: ["auslautverhaertung"],
    genre: "schule",
    text: "Auf dem Weg zur Schule gehe ich am Wald vorbei. Mein Freund Jan wartet an der Ecke. Er hat ein neues Rad. Wir gehen zusammen, bis wir am Hof ankommen. Im Unterricht malt er ein Bild von einem Berg. Seine Hand ist schnell und sicher.",
    targetWords: ["Weg", "Wald", "Freund", "Rad", "Bild", "Berg", "Hand"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-024",
    title: "Mit dem Fahrrad zum See",
    difficulty: "leicht",
    phenomena: ["dehnungs-h"],
    genre: "erlebnis",
    text: "Am Sonntag fahren wir mit dem Fahrrad zum See. Papa nimmt eine Karte mit, damit wir den Weg nicht verlieren. Unterwegs sehen wir ein Reh. Es bleibt stehen und wir sehen uns lange an. Mama holt aus der Tasche eine Banane. Ich esse sie ganz langsam, weil ich sehr Hunger habe.",
    targetWords: ["fahren", "Fahrrad", "sehen", "Reh", "stehen", "sehr"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-025",
    title: "Im Garten",
    difficulty: "leicht",
    phenomena: ["zusammensetzungen"],
    genre: "sachtext",
    text: "Im Garten gibt es viele Dinge. Der Gartenzaun schützt die Beete. Im Gewächshaus wachsen die Tomaten. Der Regenwurm lockert die Erde. Die Gießkanne steht neben der Haustür. Am Nachmittag scheint die Sonne auf den Sandkasten, wo die Kinder spielen.",
    targetWords: [
      "Gartenzaun",
      "Gewächshaus",
      "Regenwurm",
      "Gießkanne",
      "Nachmittag",
      "Sandkasten",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-026",
    title: "Ein Tag im Herbst",
    difficulty: "leicht",
    phenomena: ["gemischt", "doppelkonsonanten", "ie"],
    genre: "alltag",
    text: "Im Herbst fallen die Blätter von den Bäumen. Wir ziehen warme Jacken an und gehen in den Wald. Dort sammeln wir Kastanien und Eicheln. Mein Bruder fliegt mit dem Drachen über das Feld. Danach trinken wir zu Hause heißen Tee und essen Kuchen. Am Abend zünden wir eine Kerze an.",
    targetWords: ["fallen", "Blätter", "ziehen", "sammeln", "fliegt", "essen"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-027",
    title: "Im Schnee",
    difficulty: "mittel",
    phenomena: ["vokallaenge"],
    genre: "erlebnis",
    text: "Im Winter hat es viel geschneit. Am Samstag nehmen wir unsere Schlitten und gehen zum Hügel. Der Schnee liegt ganz weiß auf der Wiese. Mein Bruder baut einen Mann aus Schnee, und ich suche zwei Kohlen für die Augen. Papa zeigt uns, wie man den Schlitten lenkt. Wir fahren den Hang hinunter und jubeln laut. Leider bleibt Mia im Schnee stecken, und wir müssen sie herausziehen. Zum Aufwärmen gibt es heißen Tee und warme Suppe. Dann gehen wir müde heim.",
    targetWords: [
      "viel",
      "nehmen",
      "Schlitten",
      "Schnee",
      "Wiese",
      "Mann",
      "Kohlen",
      "fahren",
      "müssen",
      "Tee",
      "Suppe",
      "liegt",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-028",
    title: "Hausaufgaben",
    difficulty: "mittel",
    phenomena: ["s-ss-sz"],
    genre: "alltag",
    text: "Nach der Schule muss ich noch meine Hausaufgaben machen. Mein Fuß tut vom Fußballspielen noch weh, deshalb sitze ich lieber still. Mir ist heiß, weil ich so konzentriert arbeite. Ich weiß nicht, was das letzte Wort bedeutet, und frage Mama. Ich freue mich, dass ich so schnell fertig bin. Danach esse ich ein Stück Kuchen und trinke Saft. Draußen ist das Wetter nass und grau, deshalb bleibe ich lieber drinnen.",
    targetWords: [
      "muss",
      "Fuß",
      "Fußballspielen",
      "heiß",
      "weiß",
      "dass",
      "esse",
      "Draußen",
      "nass",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-029",
    title: "Das Klassenprojekt",
    difficulty: "mittel",
    phenomena: ["wortbausteine"],
    genre: "schule",
    text: "In der Schule beginnt unser Projekt über Tiere. Zuerst überlegen wir, was wir erforschen möchten. Die Lehrerin verteilt die Aufgaben und erklärt die Vorbereitung. Jede Gruppe entscheidet sich für ein Tier und entwirft ein Plakat. Wir besprechen, was wir verbessern können, und verändern manches. Am Ende der Woche präsentieren wir unsere Ergebnisse. Alle sind gespannt und freuen sich über die Erfahrung.",
    targetWords: [
      "beginnt",
      "erforschen",
      "verteilt",
      "erklärt",
      "Vorbereitung",
      "entscheidet",
      "entwirft",
      "besprechen",
      "verbessern",
      "verändern",
      "Ergebnisse",
      "gespannt",
      "Erfahrung",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-030",
    title: "Der Schmetterling",
    difficulty: "mittel",
    phenomena: ["ie"],
    genre: "geschichte",
    text: "Ein kleiner Schmetterling flog über die Wiese. Er suchte nach einer Blume mit süßem Saft. Plötzlich sah er ein großes Tier mit vier Beinen. Es war ein Hirsch, der ruhig im Gras lag. Der Schmetterling setzte sich auf sein Geweih und wippte hin und her. Der Hirsch ließ ihn gewähren und schlief wieder ein. So blieben beide still, bis die Sonne unterging und die Nacht kam.",
    targetWords: [
      "Wiese",
      "Tier",
      "vier",
      "ließ",
      "schlief",
      "wieder",
      "blieben",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-031",
    title: "In der Pause",
    difficulty: "mittel",
    phenomena: ["doppelkonsonanten"],
    genre: "schule",
    text: "In der Pause rennen alle Kinder auf den Schulhof. Einige spielen Fußball, andere hüpfen im Kreis oder klettern auf die Rutsche. Ich sitze mit Anna auf der Bank und esse mein Brötchen. Plötzlich rollt ein Ball zu uns herüber. Anna wirft ihn zurück, und die Jungen bedanken sich. Dann klingelt es, und wir müssen wieder in die Klasse. Die Lehrerin begrüßt uns und fragt, wer die Hausaufgabe gelöst hat.",
    targetWords: [
      "rennen",
      "Fußball",
      "klettern",
      "esse",
      "rollt",
      "Ball",
      "müssen",
      "Klasse",
      "Dann",
      "alle",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-032",
    title: "Auf dem Spielplatz",
    difficulty: "mittel",
    phenomena: ["gross-klein"],
    genre: "alltag",
    text: "Am Nachmittag gehen wir auf den Spielplatz. Dort gibt es eine Schaukel, eine Rutsche und einen Sandkasten. Meine Schwester baut eine Burg aus Sand und holt Wasser aus dem Brunnen. Ich klettere auf das Gerüst und rufe nach meinem Freund. Sein Vater sitzt auf der Bank und liest die Zeitung. Plötzlich beginnt es zu regnen, und wir rennen zum Auto. Zu Hause gibt es heißen Kakao und ein Stück Kuchen.",
    targetWords: [
      "Schaukel",
      "Rutsche",
      "Sandkasten",
      "Schwester",
      "Burg",
      "Sand",
      "Wasser",
      "Brunnen",
      "Gerüst",
      "Freund",
      "Vater",
      "Zeitung",
      "Kakao",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-033",
    title: "Ausflug in den Wald",
    difficulty: "mittel",
    phenomena: ["auslautverhaertung"],
    genre: "erlebnis",
    text: "Am Sonntag machen wir einen Ausflug in den Wald. Der Weg führt uns auf einen Berg. Von dort oben sehen wir das ganze Land und hören den Wind in den Bäumen. Mein Hund springt in den Bach und schüttelt sich danach ab. Ein Kind aus der Nachbarschaft zeigt uns ein Nest im Baum. Unterwegs finden wir einen Pilz, den wir lieber nicht anfassen. Es ist ein langer Tag, und wir sind froh, als wir am Abend das Auto erreichen.",
    targetWords: [
      "Sonntag",
      "Ausflug",
      "Wald",
      "Weg",
      "Berg",
      "Land",
      "Wind",
      "Hund",
      "Kind",
      "Tag",
      "Abend",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-034",
    title: "Beim Arzt",
    difficulty: "mittel",
    phenomena: ["dehnungs-h"],
    genre: "alltag",
    text: "Heute war ich mit Mama beim Arzt. Mein Hals tat weh, und ich hatte etwas Fieber. Der Arzt nahm einen kleinen Stab und sah mir in den Mund. Er sagte, dass ich ruhig noch drei Tage zu Hause bleiben soll. Ich durfte mir ein Bonbon aus der Dose nehmen. Mama hat mir danach einen Tee und Honig gemacht. Ohne Schmerzen fühle ich mich schon wieder besser.",
    targetWords: ["weh", "nahm", "sah", "ruhig", "nehmen", "Ohne", "fühle"],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-035",
    title: "Der Wandertag",
    difficulty: "mittel",
    phenomena: ["zusammensetzungen"],
    genre: "erlebnis",
    text: "Am Wandertag treffen wir uns um acht Uhr am Bahnhof. Jeder hat einen Rucksack mit Proviant dabei. Im Zug singen wir Lieder, bis wir an der Haltestelle aussteigen. Der Weg führt durch einen Tannenwald zu einer Burgruine. Dort machen wir Pause und essen unser Pausenbrot. Der Lehrer erzählt uns die Geschichte vom Burgherrn. Auf dem Rückweg finden wir einen Waldspielplatz und toben, bis der Bus kommt.",
    targetWords: [
      "Wandertag",
      "Rucksack",
      "Haltestelle",
      "Tannenwald",
      "Burgruine",
      "Pausenbrot",
      "Burgherrn",
      "Waldspielplatz",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-036",
    title: "Das verschwundene Fahrrad",
    difficulty: "mittel",
    phenomena: ["gemischt", "dehnungs-h", "doppelkonsonanten", "ie"],
    genre: "geschichte",
    text: "Tim wollte nach der Schule mit seinem Fahrrad zum Fußballplatz fahren. Doch als er zum Schuppen kam, war das Rad verschwunden. Er suchte hinter dem Haus, im Garten und in der Garage. Dann fragte er seine Schwester, die gerade ihre Tasche holte. Sie lachte und zeigte auf den Gartenzaun. Dort stand das Fahrrad, denn Papa hatte es gewaschen und zum Trocknen in die Sonne gestellt. Tim war erleichtert und fuhr los.",
    targetWords: [
      "wollte",
      "Fahrrad",
      "Fußballplatz",
      "fahren",
      "Schuppen",
      "Sonne",
      "gestellt",
      "fuhr",
      "denn",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-037",
    title: "Der Igel",
    difficulty: "mittel",
    phenomena: ["vokallaenge"],
    genre: "sachtext",
    text: "Der Igel ist ein nachtaktives Tier. Tagsüber schläft er in einem Laubhaufen oder unter einer Hecke. Im Herbst frisst er viele Käfer, Regenwürmer und Schnecken. So bekommt er genug Fett für den Winter. Wenn es kalt wird, rollt sich der Igel zu einer Kugel zusammen und hält Winterschlaf. Dann schlägt sein Herz nur noch ganz langsam. Erst im Frühling wacht er wieder auf und sucht nach Futter.",
    targetWords: [
      "Tier",
      "frisst",
      "bekommt",
      "Fett",
      "rollt",
      "zusammen",
      "Frühling",
      "wieder",
      "Futter",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-038",
    title: "Der Umzug",
    difficulty: "mittel",
    phenomena: ["wortbausteine"],
    genre: "alltag",
    text: "Nächste Woche ziehen wir um. Wir haben schon viele Kisten gepackt und beschriftet. Meine Eltern verkaufen das alte Sofa und besprechen die Möbel für das neue Zimmer. Ich verabschiede mich von meinen Freunden und verspreche, sie zu besuchen. Am Umzugstag erwarten wir die Helfer um acht Uhr. Sie verladen die Kisten und befestigen alles mit Gurten. Bis zum Abend ist die Wohnung leer.",
    targetWords: [
      "gepackt",
      "beschriftet",
      "verkaufen",
      "besprechen",
      "verabschiede",
      "verspreche",
      "besuchen",
      "erwarten",
      "verladen",
      "befestigen",
      "Wohnung",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-039",
    title: "Das Meer",
    difficulty: "schwer",
    phenomena: ["vokallaenge"],
    genre: "sachtext",
    text: "Das Meer bedeckt den größten Teil unserer Erde. Wer am Strand steht, sieht nur das Wasser und die Wellen, doch unter der Oberfläche leben unzählige Tiere. Seesterne kriechen über den Boden, Seepferdchen halten sich an Algen fest, und ein Hai gleitet durch die Tiefe. Zweimal am Tag kommen Ebbe und Flut. Bei Ebbe zieht sich das Wasser zurück, und man kann im Watt nach Muscheln suchen. Bei Flut steigt es wieder an und füllt die Priele. Segler und Fischer nutzen das Meer seit vielen hundert Jahren. Sie fahren mit Booten hinaus und fangen Fische, die sie später auf dem Markt verkaufen. Leider gelangt auch viel Müll ins Meer, den Tiere mit Nahrung verwechseln. Deshalb sollten wir alle darauf achten, nichts in die Natur zu werfen.",
    targetWords: [
      "Meer",
      "Seesterne",
      "Seepferdchen",
      "Tiere",
      "Tiefe",
      "Ebbe",
      "Watt",
      "Priele",
      "Booten",
      "Nahrung",
      "fahren",
      "wieder",
      "viel",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-040",
    title: "Das Picknick am Fluss",
    difficulty: "schwer",
    phenomena: ["s-ss-sz"],
    genre: "geschichte",
    text: "An einem heißen Sonntag wollte die Familie ein Picknick am Fluss machen. Papa packte Brote, Würstchen und eine große Flasche Saft in den Korb. Mama nahm die Decke mit, und Lisa vergaß fast ihren Fußball. Auf der Straße war wenig los, deshalb kamen sie schnell an. Am Ufer wuchs weiches Gras, und das Wasser glitzerte in der Sonne. Lisa zog die Schuhe aus und lief barfuß durch den nassen Sand. Plötzlich rutschte sie aus und fiel ins Wasser. Alle mussten lachen, sogar Lisa selbst. Sie war nass bis auf die Haut, aber es machte ihr großen Spaß. Zum Glück hatten sie ein Handtuch dabei. Danach aßen sie, bis nichts mehr übrig war. Auf dem Heimweg sagte Papa, dass dies der schönste Ausflug des Sommers gewesen sei.",
    targetWords: [
      "heißen",
      "Fluss",
      "große",
      "Fußball",
      "Straße",
      "Wasser",
      "barfuß",
      "nassen",
      "mussten",
      "nass",
      "großen",
      "Spaß",
      "aßen",
      "vergaß",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-041",
    title: "Die Geburtstagsfeier",
    difficulty: "schwer",
    phenomena: ["wortbausteine"],
    genre: "alltag",
    text: "Am Samstag feiert Lena ihren Geburtstag. Schon eine Woche vorher beginnt die Vorbereitung. Sie überlegt, wen sie einladen möchte, und verteilt die Einladungen in der Klasse. Ihre Mutter erledigt die Einkäufe und bereitet den Kuchen vor. Am Morgen der Feier entdeckt Lena ein Geschenk vor der Tür und freut sich über die Überraschung. Die Gäste erscheinen pünktlich und begrüßen das Geburtstagskind. Zuerst verspeisen alle den Kuchen, danach beginnen die Spiele. Beim Topfschlagen verliert einer den Überblick und verfehlt den Topf. Zum Schluss bekommt jeder Gast eine kleine Tüte mit Süßigkeiten. Am Abend verabschieden sich die Gäste und bedanken sich für den schönen Nachmittag. Lena ist müde, aber glücklich, und erzählt ihren Eltern von der Feier.",
    targetWords: [
      "Geburtstag",
      "vorher",
      "beginnt",
      "Vorbereitung",
      "verteilt",
      "erledigt",
      "bereitet",
      "entdeckt",
      "Geschenk",
      "Überraschung",
      "erscheinen",
      "pünktlich",
      "begrüßen",
      "Geburtstagskind",
      "verspeisen",
      "beginnen",
      "verliert",
      "verfehlt",
      "verabschieden",
      "bedanken",
      "glücklich",
      "erzählt",
      "bekommt",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-042",
    title: "Im Zirkus",
    difficulty: "schwer",
    phenomena: ["ie"],
    genre: "erlebnis",
    text: "Gestern waren wir im Zirkus. Schon vor dem Zelt spielte eine kleine Kapelle lustige Lieder. Im Inneren roch es nach Popcorn, und überall liefen Kinder mit Zuckerwatte herum. Zuerst liefen vier Pferde im Kreis, und ein Reiter stand aufrecht auf ihrem Rücken. Dann kam ein Clown, der immer wieder über seine viel zu großen Schuhe stolperte. Das Publikum lachte laut. Danach zeigten die Tiere ihre Kunststücke: Ein Elefant stieg auf einen Hocker, und die Seelöwen fingen Bälle mit der Nase. Ein Zauberer ließ eine Fliege verschwinden. Am besten gefiel mir die Vorstellung der Artisten, die hoch oben im Zelt über das Seil gingen. Meine Schwester hielt die Luft an, als einer fast hinunterfiel. Zum Glück fing ihn ein Netz auf. Am Ende riefen alle laut Zugabe, und wir hätten gern noch länger zugesehen.",
    targetWords: [
      "spielte",
      "Lieder",
      "liefen",
      "vier",
      "wieder",
      "viel",
      "Tiere",
      "gefiel",
      "hielt",
      "hinunterfiel",
      "ließ",
      "Fliege",
      "riefen",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-043",
    title: "Ein Besuch im Museum",
    difficulty: "schwer",
    phenomena: ["doppelkonsonanten"],
    genre: "schule",
    text: "Unsere Klasse macht einen Ausflug ins Museum. Schon im Bus sind alle aufgeregt. Eine Führerin empfängt uns und erklärt, was wir alles sehen werden. In der ersten Halle stehen riesige Knochen von Dinosauriern. Anna kann kaum glauben, dass diese Tiere so groß waren. Im nächsten Raum hängt ein Skelett von einem Wal. Wir dürfen nichts anfassen, aber wir können ganz nah herangehen. Danach gibt es eine Rallye mit vielen Fragen. Wer alle Antworten findet, bekommt am Ende eine Urkunde. Zum Schluss sitzen wir im Café und trinken Kakao. Ein Mitarbeiter schenkt uns noch Postkarten mit Bildern aus der Ausstellung. Müde, aber zufrieden, kommen wir am Nachmittag wieder in der Schule an.",
    targetWords: [
      "Klasse",
      "Halle",
      "Skelett",
      "anfassen",
      "können",
      "bekommt",
      "Schluss",
      "Ausstellung",
      "kommen",
      "Nachmittag",
      "dass",
      "alle",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-044",
    title: "Das Jahr im Wald",
    difficulty: "schwer",
    phenomena: ["gross-klein"],
    genre: "sachtext",
    text: "Im Frühling erwacht der Wald zu neuem Leben. An den Zweigen der Bäume treiben die ersten Blätter aus, und am Boden blühen Anemonen und Veilchen. Die Vögel bauen ihre Nester und füttern ihre Jungen. Im Sommer spendet das Laub kühlen Schatten, und Pilze wachsen im feuchten Moos. Rehe und Füchse suchen Nahrung für ihre Familien. Im Herbst färben sich die Blätter gelb und rot. Eichhörnchen sammeln Nüsse und Eicheln als Vorrat für die kalte Zeit. Im Winter ruht der Wald unter einer Decke aus Schnee. Viele Tiere halten dann Winterschlaf, und nur wenige bleiben aktiv. Wer im Winter durch den Wald geht, entdeckt Spuren im Schnee und hört den Wind in den kahlen Ästen.",
    targetWords: [
      "Zweigen",
      "Bäume",
      "Blätter",
      "Boden",
      "Anemonen",
      "Veilchen",
      "Vögel",
      "Nester",
      "Laub",
      "Schatten",
      "Pilze",
      "Moos",
      "Rehe",
      "Füchse",
      "Nahrung",
      "Familien",
      "Vorrat",
      "Decke",
      "Schnee",
      "Spuren",
      "Wind",
      "Ästen",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-045",
    title: "Die Rettung am Berg",
    difficulty: "schwer",
    phenomena: ["auslautverhaertung"],
    genre: "geschichte",
    text: "Am Rande des Dorfes führte ein schmaler Weg auf einen Berg. Eines Tages wanderte Ben dort mit seinem Hund hinauf. Plötzlich fing es an zu regnen, und der Wind wurde stärker. Der Hund lief voraus und bellte laut. Ben folgte ihm und sah, dass ein Kind im Gebüsch saß. Es hatte sich im Wald verlaufen und fror an den Händen. Ben nahm seine Jacke ab und legte sie dem Kind um die Schultern. Dann nahm er es an der Hand, und gemeinsam gingen sie den Weg zurück. Unterwegs trafen sie einen Mann, der mit dem Rad ins Dorf fuhr. Er rief die Eltern an, und bald war das Kind wieder zu Hause. Am Abend lobte der Bürgermeister Ben vor allen Leuten. Das Bild von Ben und seinem Hund hing noch lange im Rathaus.",
    targetWords: [
      "Weg",
      "Berg",
      "Hund",
      "Wind",
      "Kind",
      "Wald",
      "Hand",
      "Rad",
      "Abend",
      "Bild",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-046",
    title: "Ein Backtag",
    difficulty: "schwer",
    phenomena: ["dehnungs-h"],
    genre: "alltag",
    text: "Am Samstagmorgen wollen wir Kuchen backen. Mama holt Mehl, Zucker und Sahne aus dem Schrank. Ich zähle die Eier und rühre den Teig. Dabei sehe ich auf die Uhr, denn der Ofen braucht zehn Minuten zum Heizen. Mein Bruder nimmt die Form und fettet sie ein. Er ist sehr stolz, weil er das Rezept ohne Hilfe liest. Als der Kuchen fertig ist, duftet das ganze Haus. Wir lassen ihn ein wenig ruhen und decken den Tisch. Mein Bruder zählt die Teller noch einmal nach, damit nichts fehlt. Papa kommt hungrig aus dem Garten und fragt, ob er mehr als ein Stück bekommt. Zum Glück ist der Kuchen groß genug, und wir können einen Teil verschenken.",
    targetWords: [
      "Mehl",
      "Sahne",
      "zähle",
      "rühre",
      "sehe",
      "Uhr",
      "zehn",
      "sehr",
      "ohne",
      "ruhen",
      "mehr",
      "zählt",
      "fehlt",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-047",
    title: "Das Zeltlager",
    difficulty: "schwer",
    phenomena: ["zusammensetzungen"],
    genre: "erlebnis",
    text: "In den Sommerferien fuhr ich mit meiner Gruppe ins Zeltlager. Schon am Bahnhof wartete der Reisebus, der uns zum Zeltplatz brachte. Dort bauten wir gemeinsam unsere Schlafzelte auf und rollten die Schlafsäcke aus. Am Abend saßen wir am Lagerfeuer und rösteten Stockbrot. Jemand erzählte eine Gruselgeschichte, und wir kuschelten uns eng zusammen. Am nächsten Morgen weckte uns die Trillerpfeife des Betreuers. Nach dem Frühstück machten wir eine Wanderung zum Badesee. Dort gab es eine Wasserrutsche und ein Volleyballnetz. Am Mittwoch gab es eine Nachtwanderung mit Taschenlampen, und wir hörten den Waldkauz rufen. Nachmittags bastelten wir Freundschaftsbänder und spielten Fußball auf der Wiese. In der letzten Nacht regnete es so stark, dass unser Zelt beinahe davonschwamm.",
    targetWords: [
      "Sommerferien",
      "Zeltlager",
      "Reisebus",
      "Zeltplatz",
      "Schlafzelte",
      "Schlafsäcke",
      "Lagerfeuer",
      "Stockbrot",
      "Gruselgeschichte",
      "Trillerpfeife",
      "Frühstück",
      "Wasserrutsche",
      "Volleyballnetz",
      "Freundschaftsbänder",
      "Nachtwanderung",
      "Taschenlampen",
      "Waldkauz",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-048",
    title: "Der Fuchs",
    difficulty: "schwer",
    phenomena: ["gemischt", "doppelkonsonanten", "ie", "dehnungs-h"],
    genre: "sachtext",
    text: "Der Rotfuchs lebt in Wäldern, auf Feldern und manchmal sogar in großen Städten. Tagsüber ruht er in seinem Bau, und erst in der Dämmerung geht er auf Nahrungssuche. Er frisst Mäuse, Beeren, Käfer und manchmal auch Abfälle. Mit seinen scharfen Ohren hört er selbst ein leises Rascheln im Gras. Wenn er eine Maus entdeckt, springt er hoch in die Luft und stürzt sich auf sie. Im Frühling bekommt die Füchsin vier bis sechs Junge. Sie spielen vor dem Bau und lernen von ihrer Mutter, wie man jagt. Im Winter, wenn Schnee liegt, hört der Fuchs sogar Mäuse unter der weißen Decke. Füchse sind sehr scheue Tiere. Wer ruhig bleibt und genau hinsieht, kann sie manchmal beim Mäusefangen beobachten.",
    targetWords: [
      "ruht",
      "Dämmerung",
      "Nahrungssuche",
      "frisst",
      "Abfälle",
      "Ohren",
      "bekommt",
      "vier",
      "Mutter",
      "Tiere",
      "ruhig",
      "hinsieht",
      "sehr",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-049",
    title: "Die Projektwoche",
    difficulty: "schwer",
    phenomena: ["wortbausteine"],
    genre: "schule",
    text: "In der Projektwoche beschäftigt sich unsere Klasse mit dem Thema Wasser. Am Montag besprechen wir, was wir erreichen wollen. Jede Gruppe erhält eine Aufgabe und verteilt die Rollen. Meine Gruppe untersucht, wie sauber das Wasser im Bach ist. Wir entnehmen Proben, vergleichen sie und notieren unsere Beobachtungen. Am Dienstag besuchen wir ein Wasserwerk und erkunden die Anlage. Am Mittwoch erfahren wir von einer Expertin, wie man Wasser reinigt. Sie erklärt die Verschmutzung und zeigt Möglichkeiten zur Verbesserung. Danach bereiten wir ein Plakat vor und üben die Präsentation. Am Freitag stellen wir unsere Ergebnisse den Eltern vor. Die Gäste bewundern die Experimente, und wir sind erleichtert, dass nichts misslungen ist. Zum Abschluss bekommt jeder eine Urkunde und verabschiedet sich zufrieden.",
    targetWords: [
      "beschäftigt",
      "besprechen",
      "erreichen",
      "erhält",
      "verteilt",
      "untersucht",
      "entnehmen",
      "vergleichen",
      "Beobachtungen",
      "erfahren",
      "erklärt",
      "Verschmutzung",
      "Verbesserung",
      "besuchen",
      "erkunden",
      "bereiten",
      "Ergebnisse",
      "bewundern",
      "erleichtert",
      "Abschluss",
      "bekommt",
      "verabschiedet",
    ],
    usage: ["frei", "wortspeicher"],
  },
  {
    id: "TXT-050",
    title: "Auf dem Bauernhof",
    difficulty: "schwer",
    phenomena: ["s-ss-sz"],
    genre: "alltag",
    text: "In den Ferien besuchen wir einen Bauernhof. Schon an der Straße riecht es nach frischem Gras und warmem Stroh. Die Bäuerin begrüßt uns und führt uns durch den Stall. Dort fressen die Kühe ihr Futter, und ein kleines Kalb saugt an einer Flasche. Ich darf einen Eimer Wasser zu den Schweinen tragen, doch der Eimer ist so groß, dass ich ihn kaum anheben kann. Danach dürfen wir die Eier einsammeln. Wir müssen vorsichtig sein, damit nichts kaputtgeht. Zum Mittagessen gibt es Kartoffeln mit Soße und frischen Salat. Alles schmeckt köstlich, und ich esse zwei Portionen. Nachmittags liegen wir im Gras und genießen die Ruhe. Es ist heiß, und unsere Füße sind staubig. Zum Abschied schenkt uns die Bäuerin ein Glas Honig.",
    targetWords: [
      "Straße",
      "begrüßt",
      "fressen",
      "Wasser",
      "groß",
      "müssen",
      "Mittagessen",
      "Soße",
      "esse",
      "genießen",
      "heiß",
      "Füße",
      "dass",
    ],
    usage: ["frei", "wortspeicher"],
  },
];

export const TEXTBOX_TEXTS: readonly TextboxText[] = DRAFT_TEXTS.map((text) =>
  textboxTextSchema.parse(text),
);

export function getTextboxText(id: string): TextboxText | undefined {
  return TEXTBOX_TEXTS.find((text) => text.id === id);
}
